### ISSUE TITLE
 not allowed to perform SYSTEM_ALERT_WINDOW

### ISSUE THREAD

**Issue by oversecio** [oversecio/oversec_crypto#13]
Application: io.oversec.one
Version: 1001000
Build-Type: release
Flavor: google
Android-Version: 23
Android-Build: samsung/hero2ltexx/hero2lte:6.0.1/MMB29K/G935FXXU1BPH6:user/release-keys
Hardware: samsung/samsung / SM-G935F / hero2ltexx
Open-Keychain-Version: 41010
-------------------------
Thread: UI
Stacktrace:
java.lang.SecurityException: io.oversec.one from uid 10207 not allowed to perform SYSTEM_ALERT_WINDOW
at android.os.Parcel.readException(Parcel.java:1620)
at android.os.Parcel.readException(Parcel.java:1573)
at android.view.IWindowSession$Stub$Proxy.addToDisplay(IWindowSession.java:791)
at android.view.ViewRootImpl.setView(ViewRootImpl.java:812)
at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:337)
at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:91)
at io.oversec.one.ui.h.a(SourceFile:288)
at io.oversec.one.a.handleMessage(SourceFile:28226)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:158)
at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by oversecio** [comment]
now handling gracefully and requesting permission to draw over other apps
