### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by oversecio** [oversecio/oversec_crypto#14]
Application: io.oversec.one
Version: 1001000
Build-Type: release
Flavor: google
Android-Version: 19
Android-Build: zte/N9130/speed:4.4.4/KTU84P/20160714.085354.7052:user/release-keys
Hardware: zte/zte / N9130 / N9130
Open-Keychain-Version: 41010
-------------------------
Thread: UI
Stacktrace:
java.lang.NullPointerException
at io.oversec.one.a.f(SourceFile:50107)
at io.oversec.one.a.handleMessage(SourceFile:39196)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:136)
at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by oversecio** [comment]
turned out to be a rare racecondition. Fixed in 1.1.1
