### ISSUE TITLE
Oversec crashes client apps when using PGP encryption and "inivisible" encoding

### ISSUE THREAD

**Issue by oversecio** [oversecio/oversec_crypto#15]
.. when writing encoded text back into the input field.

E/AndroidRuntime( 4507): FATAL EXCEPTION: main
E/AndroidRuntime( 4507): Process: com.google.android.apps.messaging, PID: 4507
E/AndroidRuntime( 4507): java.lang.IndexOutOfBoundsException: setSpan (4402 ... 4402) ends beyond length 2000
E/AndroidRuntime( 4507): 	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1018)
E/AndroidRuntime( 4507): 	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:611)
E/AndroidRuntime( 4507): 	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:607)
E/AndroidRuntime( 4507): 	at android.text.Selection.setSelection(Selection.java:76)
E/AndroidRuntime( 4507): 	at android.text.Selection.setSelection(Selection.java:87)
E/AndroidRuntime( 4507): 	at android.widget.EditText.setSelection(EditText.java:99)
E/AndroidRuntime( 4507): 	at android.widget.EditText.performAccessibilityAction(EditText.java:145)
E/AndroidRuntime( 4507): 	at android.view.AccessibilityInteractionController.perfromAccessibilityActionUiThread(AccessibilityInteractionController.java:626)
E/AndroidRuntime( 4507): 	at android.view.AccessibilityInteractionController.access$500(AccessibilityInteractionController.java:53)
E/AndroidRuntime( 4507): 	at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1149)
E/AndroidRuntime( 4507): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 4507): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 4507): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime( 4507): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4507): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 4507): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime( 4507): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by oversecio** [comment]
Happens with new Google Messenger (com.google.android.apps.messaging) as well as with "Hangouts"

**Comment by oversecio** [comment]
This is not related to PGP encryption per se, but related to the sheer length of PGP encrypted messages!

**Comment by oversecio** [comment]
This due to the fact that e.g. "Google Messenger" has a "maxLength=2000" set to the message text input field, so there's nothing we can do except asking the user to NOT use PGP encryption
