### ISSUE TITLE
Crash / NullPointerException when showing list of purchases

### ISSUE THREAD

**Issue by oversecio** [oversecio/oversec_crypto#26]
Application: io.oversec.one
Version: 1003002
Build-Type: release
Flavor: google
Android-Version: 24
Android-Build: google/bullhead/bullhead:7.0/NRD90R/3141966:user/release-keys
Hardware: google/LGE / Nexus 5X / bullhead
Open-Keychain-Version: 41010
-------------------------
Thread: main
Stacktrace:
java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.oversec.one.iab.k.e' on a null object reference
at io.oversec.one.ui.j$a.onBindViewHolder(SourceFile:4036)
at android.support.v7.widget.RecyclerView$a.onBindViewHolder(SourceFile:5471)
at android.support.v7.widget.RecyclerView$a.bindViewHolder(SourceFile:5504)
at android.support.v7.widget.RecyclerView$m.b(SourceFile:11741)
at android.support.v7.widget.LinearLayoutManager$c.a(SourceFile:1994)
at android.support.v7.widget.LinearLayoutManager.a(SourceFile:1390)
at android.support.v7.widget.LinearLayoutManager.a(SourceFile:1353)
at android.support.v7.widget.LinearLayoutManager.c(SourceFile:574)
at android.support.v7.widget.RecyclerView.x(SourceFile:3028)
at android.support.v7.widget.RecyclerView.v(SourceFile:2906)
at android.support.v7.widget.RecyclerView.onLayout(SourceFile:3283)
at android.view.View.layout(View.java:17519)
at android.view.ViewGroup.layout(ViewGroup.java:5612)
at android.support.v4.view.ViewPager.onLayout(SourceFile:1695)
at android.view.View.layout(View.java:17519)
at android.view.ViewGroup.layout(ViewGroup.java:5612)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
at android.view.View.layout(View.java:17519)
at android.view.ViewGroup.layout(ViewGroup.java:5612)
at android.support.design.widget.CoordinatorLayout.a(SourceFile:11091)
at android.support.design.widget.CoordinatorLayout.onLayout(SourceFile:815)
at android.view.View.layout(View.java:17519)
at android.view.ViewGroup.layout(ViewGroup.java:5612)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
at android.view.View.layout(View.java:17519)
at android.view.ViewGroup.layout(ViewGroup.java:5612)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
at android.view.View.layout(View.java:17519)
at android.view.ViewGroup.layout(ViewGroup.java:5612)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
at android.view.View.layout(View.java:17519)
at android.view.ViewGroup.layout(ViewGroup.java:5612)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
at android.view.View.layout(View.java:17519)
at android.view.ViewGroup.layout(ViewGroup.java:5612)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
at com.android.internal.policy.DecorView.onLayout(DecorView.java:724)
at android.view.View.layout(View.java:17519)
at android.view.ViewGroup.layout(ViewGroup.java:5612)
at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2342)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2069)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6301)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
at android.view.Choreographer.doCallbacks(Choreographer.java:683)
at android.view.Choreographer.doFrame(Choreographer.java:619)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6077)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by oversecio** [comment]
fixed
