### ISSUE TITLE
NPE in ZXCVBN library when checking password strength

### ISSUE THREAD

**Issue by oversecio** [oversecio/oversec_crypto#27]
Application: io.oversec.one
Version: 1003003
Build-Type: release
Flavor: google
Android-Version: 23

-------------------------
Thread: main
Stacktrace:
java.lang.NullPointerException: Attempt to read from field 'int com.nulabinc.zxcvbn.matchers.Match.i' on a null object reference
at com.nulabinc.zxcvbn.Scoring.unwind(SourceFile:101)
at com.nulabinc.zxcvbn.Scoring.mostGuessableMatchSequence(SourceFile:46)
at com.nulabinc.zxcvbn.Scoring.mostGuessableMatchSequence(SourceFile:20)
at com.nulabinc.zxcvbn.Zxcvbn.measure(SourceFile:30)
at com.nulabinc.zxcvbn.Zxcvbn.measure(SourceFile:14)
at io.oversec.one.crypto.ui.NewPasswordInputDialog.calcPasswordEntropy(SourceFile:278)
at io.oversec.one.crypto.ui.NewPasswordInputDialog.access$300(SourceFile:30)
at io.oversec.one.crypto.ui.NewPasswordInputDialog$6.onTextChanged(SourceFile:154)
at android.widget.TextView.sendOnTextChanged(TextView.java:9237)
at android.widget.TextView.handleTextChanged(TextView.java:9315)
at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:12002)
at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1037)
at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:563)
at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:494)
at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:34)
at android.widget.TextView.paste(TextView.java:11231)
at android.widget.TextView.onTextContextMenuItem(TextView.java:10776)
at android.widget.Editor$TextActionModeCallback.onActionItemClicked(Editor.java:3670)
at com.android.internal.policy.PhoneWindow$DecorView$ActionModeCallback2Wrapper.onActionItemClicked(PhoneWindow.java:4219)
at com.android.internal.view.FloatingActionMode$4.onMenuItemSelected(FloatingActionMode.java:108)
at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:801)
at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:155)
at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:954)
at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:944)
at com.android.internal.view.FloatingActionMode$5.onMenuItemClick(FloatingActionMode.java:136)
at com.android.internal.widget.FloatingToolbar$FloatingToolbarMainPanel$1.onClick(FloatingToolbar.java:1284)
at android.view.View.performClick(View.java:5702)
at android.widget.TextView.performClick(TextView.java:10888)
at android.view.View$PerformClick.run(View.java:22541)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:7229)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by oversecio** [comment]
Note: The user seems to have *pasted* a text into the input field - that may be the reason why he's the only one experiencing this problem.

**Comment by oversecio** [comment]
Can't reproduce, reported issue:

https://github.com/nulab/zxcvbn4j/issues/19

(for now, catching the exception and returning 0 entropy)

**Comment by oversecio** [comment]
Has been fixed upstream, however the current release has a new problem when loading resource bundles ( https://github.com/nulab/zxcvbn4j/issues/21 ), so for now sticking with 1.1.1 and catching the exception

**Comment by oversecio** [comment]
fixed
