### ISSUE TITLE
NPE when comparing tooltip IDs

### ISSUE THREAD

**Issue by oversecio** [oversecio/oversec_crypto#28]
Application: io.oversec.one
Version: 1003003
Build-Type: release
Flavor: google
Android-Version: 23
Open-Keychain-Version: 41010
-------------------------
Thread: UI
Stacktrace:
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
at io.oversec.one.ui.h.a(SourceFile:839)
at io.oversec.one.ui.h.a(SourceFile:22822)
at io.oversec.one.a.a(SourceFile:815)
at io.oversec.one.ovl.n.a(SourceFile:118)
at io.oversec.one.a.handleMessage(SourceFile:46132)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:158)
at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by oversecio** [comment]
fixed
