### ISSUE TITLE
crash when saving fragment state

### ISSUE THREAD

**Issue by oversecio** [oversecio/oversec_crypto#36]
Application: io.oversec.one
Version: 1003012
Build-Type: release
Flavor: google
Android-Version: 23
Open-Keychain: NOT INSTALLED
-------------------------
Thread: main
Stacktrace:
java.lang.NullPointerException: Attempt to invoke virtual method 'long[] io.oversec.one.crypto.gpg.GpgEncryptionParams.getAllPublicKeyIds()' on a null object reference
at io.oversec.one.ui.a.b.saveState(SourceFile:707)
at io.oversec.one.ui.EncryptionParamsActivity.onSaveInstanceState(SourceFile:467)
at android.app.Activity.performSaveInstanceState(Activity.java:1303)
at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1290)
at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4131)
at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3524)
at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3593)

**Comment by oversecio** [comment]
Couldn't really reproduce it, but added an Exception Handler so that at least it won't crash the whole app.
