### ISSUE TITLE
No Activity found to handle Intent { act=android.settings.ACCESSIBILITY_SETTINGS }

### ISSUE THREAD

**Issue by oversecio** [oversecio/oversec_crypto#38]
Application: io.oversec.one
Version: 1003013
Build-Type: release
Flavor: google
Android-Version: 22
Android-Build: MetroPCS/m1_mpcs_us/m1:5.1.1/LMY47V/16323171978d9:user/release-keys
Hardware: MetroPCS/LGE / LGMS330 / m1_mpcs_us
Open-Keychain-Version: 42400
-------------------------
Thread: main
Stacktrace:
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.settings.ACCESSIBILITY_SETTINGS }
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1781)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1618)
at android.app.Activity.startActivityFromFragment(Activity.java:4416)
at android.app.Fragment.startActivityForResult(Fragment.java:1109)
at android.app.Fragment.startActivityForResult(Fragment.java:1093)
at io.oversec.one.ui.e.a(SourceFile:292)
at io.oversec.one.ui.e.onCreateView(SourceFile:281)

**Comment by oversecio** [comment]
also this:

Thread: IntentService[oversec_intent_service]
Stacktrace:
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.settings.ACCESSIBILITY_SETTINGS flg=0x10000000 }
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1781)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1501)
at android.app.ContextImpl.startActivity(ContextImpl.java:1404)
at android.app.ContextImpl.startActivity(ContextImpl.java:1386)
at android.content.ContextWrapper.startActivity(ContextWrapper.java:323)
at io.oversec.one.OversecIntentService.onHandleIntent(SourceFile:57)
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by oversecio** [comment]
Probably a result of heavy LG patching. Need to get hold of such a device. 
In any case need to catch this and show a nicer error message

**Comment by oversecio** [comment]
implemented a workaround to show a warning/help Dialog instead of crashing.

Still need to get hold of such a device and see if 
* there is an Accessibility settings page at all
* there's an intent to bring it up
