### ISSUE TITLE
unidentified crash reported by user

### ISSUE THREAD

**Issue by oversecio** [oversecio/oversec_crypto#39]
Application: io.oversec.one
Version: 1003013
Android-Version: 22
Open-Keychain: NOT INSTALLED
-------------------------
Thread: main
Stacktrace:
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.accessibility.AccessibilityNodeInfo.getChildCount()' on a null object reference
at io.oversec.one.acs.c.onAccessibilityEvent(SourceFile:315)
at android.accessibilityservice.AccessibilityService$1.onAccessibilityEvent(AccessibilityService.java:659)
at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:752)
at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
at android.os.Handler.dispatchMessage(Handler.java:102)

**Comment by oversecio** [comment]
fixed
