### ISSUE TITLE
crash when switching to secondary user

### ISSUE THREAD

**Issue by oversecio** [oversecio/oversec_crypto#40]
When switching to a secondary user, a "Oversec has stopped" dialog is shown - but Oversec seems to get retsarted and works well thereafter. 
Need to investigate...

**Comment by oversecio** [comment]
can't reproduce anymore....

**Comment by oversecio** [comment]
now happened when switching BACK from secondary user to main user:

Thread: main
Stacktrace:
java.lang.SecurityException: Call from user 0 as user -2 without permission INTERACT_ACROSS_USERS or INTERACT_ACROSS_USERS_FULL not allowed.
at android.os.Parcel.readException(Parcel.java:1546)
at android.os.Parcel.readException(Parcel.java:1499)
at android.accessibilityservice.IAccessibilityServiceConnection$Stub$Proxy.findAccessibilityNodeInfoByAccessibilityId(IAccessibilityServiceConnection.java:302)
at android.view.accessibility.AccessibilityInteractionClient.findAccessibilityNodeInfoByAccessibilityId(AccessibilityInteractionClient.java:286)
at android.view.accessibility.AccessibilityRecord.getSource(AccessibilityRecord.java:166)
at io.oversec.one.acs.OversecAccessibilityService.recordToString(OversecAccessibilityService.java:1095)
at io.oversec.one.acs.OversecAccessibilityService.eventToString(OversecAccessibilityService.java:1142)
at io.oversec.one.acs.OversecAccessibilityService.onAccessibilityEvent(OversecAccessibilityService.java:307)
at android.accessibilityservice.AccessibilityService$1.onAccessibilityEvent(AccessibilityService.java:659)
at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:752)
at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
