### ISSUE TITLE
Strange crash - investigating

### ISSUE THREAD

**Issue by oversecio** [oversecio/oversec_crypto#44]
Application: io.oversec.one
Version: 1003014
Build-Type: release
Flavor: google
Android-Version: 25
Android-Build: OnePlus/OnePlus3/OnePlus3T:7.1.1/NMF26F/03061311:user/release-keys
Hardware: OnePlus/OnePlus / ONEPLUS A3003 / OnePlus3
Open-Keychain-Version: 42400
-------------------------
Thread: main
Stacktrace:
java.lang.RuntimeException: Unable to start activity ComponentInfo{io.oversec.one/io.oversec.one.ui.MainActivity}: java.lang.IllegalArgumentException: android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{io.oversec.one/io.oversec.one.MainActivityLauncher}
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2728)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2814)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6290)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: java.lang.IllegalArgumentException: android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{io.oversec.one/io.oversec.one.MainActivityLauncher}
at android.support.v4.b.x.b(SourceFile:284)
at android.support.v7.a.l.a(SourceFile:152)
at android.support.v7.a.j.a(SourceFile:46)
at android.support.v7.a.e.onCreate(SourceFile:73)
at io.oversec.one.ui.MainActivity.onCreate(SourceFile:128)
at android.app.Activity.performCreate(Activity.java:6760)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2681)
... 9 more
Caused by: android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{io.oversec.one/io.oversec.one.MainActivityLauncher}
at android.app.ApplicationPackageManager.getActivityInfo(ApplicationPackageManager.java:410)
at android.support.v4.b.x.b(SourceFile:301)
at android.support.v4.b.x.b(SourceFile:281)
... 16 more

**Comment by oversecio** [comment]
Manually deobfuscated stacktrace:

Caused by: java.lang.IllegalArgumentException: android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{io.oversec.one/io.oversec.one.MainActivityLauncher}
at android.support.v4.app.NavUtils.getParentActivityName(SourceFile:284)
at android.support.v7.app.AppCompatDelegateImplV7.onCreate(SourceFile:152)
at android.support.v7.a.j.a(SourceFile:46)
at android.support.v7.a.e.onCreate(SourceFile:73)
at io.oversec.one.ui.MainActivity.onCreate(SourceFile:128)
at android.app.Activity.performCreate(Activity.java:6760)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2681)
... 9 more
Caused by: android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{io.oversec.one/io.oversec.one.MainActivityLauncher}
at android.app.ApplicationPackageManager.getActivityInfo(ApplicationPackageManager.java:410)
at android.support.v4.app.NavUtils.getParentActivityName(SourceFile:301)
at android.support.v4.app.NavUtils.getParentActivityName(SourceFile:281)
... 16 more
