### ISSUE TITLE
NPE reported by user

### ISSUE THREAD

**Issue by oversecio** [oversecio/oversec_crypto#48]
Application: io.oversec.one
Version: 1003015
Build-Type: release
Flavor: google
Android-Version: 23
Android-Build: 360/QK1503_M02/QK1503_M02:6.0/M5K/6.0.068.P1.161026.1503_M02-OM:user/release-keys
Hardware: 360/360 / 1503-M02 / QK1503_M02
Open-Keychain-Version: 44100
-------------------------
Thread: UI
Stacktrace:
java.lang.NullPointerException: Attempt to invoke virtual method 'void io.oversec.one.acs.c.a(io.oversec.one.acs.c$b)' on a null object reference
at io.oversec.one.a.handleMessage(SourceFile:50092)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:207)
at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by oversecio** [comment]
not sure why this happened [must be a strange race condition], but added try/catch to prevent crash
