### ISSUE TITLE
OutOfMemoryError related to ColorSeekBar

### ISSUE THREAD

**Issue by oversecio** [oversecio/oversec_crypto#8]
Application: io.oversec.one
Version: 1000000
Build-Type: release
Flavor: google
Android-Version: 21
Android-Build: Xiaomi/hennessy/hennessy:5.0.2/LRX22G/V7.3.1.0.LHNCNDD:user/release-keys
Hardware: Xiaomi/Xiaomi / Redmi Note 3 / hennessy
Open-Keychain-Version: 41010
-------------------------
Thread: main
Stacktrace:
java.lang.OutOfMemoryError: Failed to allocate a 642060 byte allocation with 369200 free bytes and 360KB until OOM
at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
at android.graphics.Bitmap.nativeCreate(Native Method)
at android.graphics.Bitmap.createBitmap(Bitmap.java)
at android.graphics.Bitmap.createBitmap(Bitmap.java)
at android.graphics.Bitmap.createBitmap(Bitmap.java)
at io.oversec.one.ui.ColorSeekBar.onSizeChanged(SourceFile:185)

**Comment by oversecio** [comment]
Ohh, just realized that the whle ColorSeekbar drawing is quite "suboptimal" (a lot of stuff instantiated in every onDraw call). (Credits to https://github.com/rtugeek/ColorSeekBar ;:-)

For now only removing that strange clearing by transparent bitmap thing....
